# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\windows.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1378, 827)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(780, 90, 351, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit2.setGeometry(QtCore.QRect(780, 170, 351, 31))
        self.lineEdit2.setObjectName("lineEdit2")
        self.lineEdit3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit3.setGeometry(QtCore.QRect(780, 260, 351, 31))
        self.lineEdit3.setObjectName("lineEdit3")
        self.lineEdit4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit4.setGeometry(QtCore.QRect(780, 350, 351, 31))
        self.lineEdit4.setObjectName("lineEdit4")
        self.lineEdit5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit5.setGeometry(QtCore.QRect(780, 420, 351, 31))
        self.lineEdit5.setObjectName("lineEdit5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(780, 550, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(910, 480, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 101, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(780, 60, 71, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(780, 140, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(780, 230, 71, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(780, 310, 71, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(780, 390, 71, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(780, 480, 111, 21))
        self.label_7.setObjectName("label_7")
        self.ImageName = QtWidgets.QLabel(self.centralwidget)
        self.ImageName.setGeometry(QtCore.QRect(910, 500, 111, 21))
        self.ImageName.setObjectName("ImageName")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(780, 500, 111, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(780, 520, 111, 21))
        self.label_9.setObjectName("label_9")
        self.NumName = QtWidgets.QLabel(self.centralwidget)
        self.NumName.setGeometry(QtCore.QRect(910, 520, 111, 21))
        self.NumName.setObjectName("NumName")
        self.AddButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.AddButton_1.setGeometry(QtCore.QRect(1140, 90, 31, 31))
        self.AddButton_1.setObjectName("AddButton_1")
        self.AddButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.AddButton_2.setGeometry(QtCore.QRect(1140, 170, 31, 31))
        self.AddButton_2.setObjectName("AddButton_2")
        self.AddButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.AddButton_3.setGeometry(QtCore.QRect(1140, 260, 31, 31))
        self.AddButton_3.setObjectName("AddButton_3")
        self.AddButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.AddButton_4.setGeometry(QtCore.QRect(1140, 350, 31, 31))
        self.AddButton_4.setObjectName("AddButton_4")
        self.AddButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.AddButton_5.setGeometry(QtCore.QRect(1140, 420, 31, 31))
        self.AddButton_5.setObjectName("AddButton_5")
        self.listlistview = QtWidgets.QListView(self.centralwidget)
        self.listlistview.setGeometry(QtCore.QRect(1180, 60, 181, 621))
        self.listlistview.setObjectName("listlistview")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(1180, 30, 101, 21))
        self.label_10.setObjectName("label_10")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 30, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 70, 761, 721))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 742, 702))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ImageLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ImageLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.ImageLabel.setText("")
        self.ImageLabel.setObjectName("ImageLabel")
        self.horizontalLayout.addWidget(self.ImageLabel)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.S1_1 = QtWidgets.QComboBox(self.centralwidget)
        self.S1_1.setGeometry(QtCore.QRect(850, 50, 81, 41))
        self.S1_1.setObjectName("S1_1")
        self.S1_1.addItem("")
        self.S1_1.addItem("")
        self.S1_1.addItem("")
        self.S1_1.addItem("")
        self.S1_1.addItem("")
        self.S1_1.addItem("")
        self.S1_1.addItem("")
        self.S1_1.addItem("")
        self.S1_2 = QtWidgets.QComboBox(self.centralwidget)
        self.S1_2.setGeometry(QtCore.QRect(940, 50, 121, 41))
        self.S1_2.setObjectName("S1_2")
        self.S1_2.addItem("")
        self.S1_2.addItem("")
        self.S1_2.addItem("")
        self.S1_2.addItem("")
        self.S2_2 = QtWidgets.QComboBox(self.centralwidget)
        self.S2_2.setGeometry(QtCore.QRect(940, 130, 121, 41))
        self.S2_2.setObjectName("S2_2")
        self.S2_2.addItem("")
        self.S2_2.addItem("")
        self.S2_2.addItem("")
        self.S2_2.addItem("")
        self.S2_2.addItem("")
        self.S2_2.addItem("")
        self.S2_2.addItem("")
        self.S2_2.addItem("")
        self.S2_2.addItem("")
        self.S2_1 = QtWidgets.QComboBox(self.centralwidget)
        self.S2_1.setGeometry(QtCore.QRect(850, 130, 81, 41))
        self.S2_1.setObjectName("S2_1")
        self.S2_1.addItem("")
        self.S2_1.addItem("")
        self.S2_1.addItem("")
        self.S2_1.addItem("")
        self.S2_1.addItem("")
        self.S2_1.addItem("")
        self.S2_1.addItem("")
        self.S2_1.addItem("")
        self.S3_2 = QtWidgets.QComboBox(self.centralwidget)
        self.S3_2.setGeometry(QtCore.QRect(940, 220, 121, 41))
        self.S3_2.setObjectName("S3_2")
        self.S3_2.addItem("")
        self.S3_2.addItem("")
        self.S3_2.addItem("")
        self.S3_2.addItem("")
        self.S3_2.addItem("")
        self.S3_2.addItem("")
        self.S3_2.addItem("")
        self.S3_2.addItem("")
        self.S3_2.addItem("")
        self.S3_1 = QtWidgets.QComboBox(self.centralwidget)
        self.S3_1.setGeometry(QtCore.QRect(850, 220, 81, 41))
        self.S3_1.setObjectName("S3_1")
        self.S3_1.addItem("")
        self.S3_1.addItem("")
        self.S3_1.addItem("")
        self.S3_1.addItem("")
        self.S3_1.addItem("")
        self.S3_1.addItem("")
        self.S3_1.addItem("")
        self.S3_1.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1378, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "JUMP"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">标注图片</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">sentence1</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">sentence2</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">sentence3</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">sentence4</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">sentence5</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#5500ff;\">跳转至指定位置</span></p></body></html>"))
        self.ImageName.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#5500ff;\">当前图片名称</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#5500ff;\">当前个数</span></p></body></html>"))
        self.NumName.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.AddButton_1.setText(_translate("MainWindow", "A"))
        self.AddButton_2.setText(_translate("MainWindow", "A"))
        self.AddButton_3.setText(_translate("MainWindow", "A"))
        self.AddButton_4.setText(_translate("MainWindow", "A"))
        self.AddButton_5.setText(_translate("MainWindow", "A"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#ff0000;\">工作列表</span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "打开文件夹"))
        self.S1_1.setItemText(0, _translate("MainWindow", "long wide"))
        self.S1_1.setItemText(1, _translate("MainWindow", "short wide"))
        self.S1_1.setItemText(2, _translate("MainWindow", "long slim"))
        self.S1_1.setItemText(3, _translate("MainWindow", "short slim"))
        self.S1_1.setItemText(4, _translate("MainWindow", "long"))
        self.S1_1.setItemText(5, _translate("MainWindow", "short"))
        self.S1_1.setItemText(6, _translate("MainWindow", "wide"))
        self.S1_1.setItemText(7, _translate("MainWindow", "slim"))
        self.S1_2.setItemText(0, _translate("MainWindow", "green"))
        self.S1_2.setItemText(1, _translate("MainWindow", "blue"))
        self.S1_2.setItemText(2, _translate("MainWindow", "black"))
        self.S1_2.setItemText(3, _translate("MainWindow", "yellow"))
        self.S2_2.setItemText(0, _translate("MainWindow", "is a village"))
        self.S2_2.setItemText(1, _translate("MainWindow", "is a city"))
        self.S2_2.setItemText(2, _translate("MainWindow", "are many buidings"))
        self.S2_2.setItemText(3, _translate("MainWindow", "are many trees"))
        self.S2_2.setItemText(4, _translate("MainWindow", "is a forest"))
        self.S2_2.setItemText(5, _translate("MainWindow", "is a open field"))
        self.S2_2.setItemText(6, _translate("MainWindow", "is a wasteland"))
        self.S2_2.setItemText(7, _translate("MainWindow", "are hilly areas"))
        self.S2_2.setItemText(8, _translate("MainWindow", "is a port"))
        self.S2_1.setItemText(0, _translate("MainWindow", "top"))
        self.S2_1.setItemText(1, _translate("MainWindow", "bottom"))
        self.S2_1.setItemText(2, _translate("MainWindow", "left"))
        self.S2_1.setItemText(3, _translate("MainWindow", "right"))
        self.S2_1.setItemText(4, _translate("MainWindow", "top left"))
        self.S2_1.setItemText(5, _translate("MainWindow", "top right"))
        self.S2_1.setItemText(6, _translate("MainWindow", "bottom left"))
        self.S2_1.setItemText(7, _translate("MainWindow", "bottom right"))
        self.S3_2.setItemText(0, _translate("MainWindow", "a village is"))
        self.S3_2.setItemText(1, _translate("MainWindow", "a city is"))
        self.S3_2.setItemText(2, _translate("MainWindow", "many buidings are"))
        self.S3_2.setItemText(3, _translate("MainWindow", "many trees are"))
        self.S3_2.setItemText(4, _translate("MainWindow", "a forest is"))
        self.S3_2.setItemText(5, _translate("MainWindow", "a open field is"))
        self.S3_2.setItemText(6, _translate("MainWindow", "a wasteland is"))
        self.S3_2.setItemText(7, _translate("MainWindow", "hilly area is"))
        self.S3_2.setItemText(8, _translate("MainWindow", "a port is"))
        self.S3_1.setItemText(0, _translate("MainWindow", "top"))
        self.S3_1.setItemText(1, _translate("MainWindow", "bottom"))
        self.S3_1.setItemText(2, _translate("MainWindow", "left"))
        self.S3_1.setItemText(3, _translate("MainWindow", "right"))
        self.S3_1.setItemText(4, _translate("MainWindow", "top left"))
        self.S3_1.setItemText(5, _translate("MainWindow", "top right"))
        self.S3_1.setItemText(6, _translate("MainWindow", "bottom left"))
        self.S3_1.setItemText(7, _translate("MainWindow", "bottom right"))

